# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Luo_Jia_Li_Xian_Ji
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(Luo_Jia_Li_Xian_Ji.pri)
win32:RC_FILE = Luo_Jia_Li_Xian_Ji.rc
